#!/bin/bash

function remove_remote() {
  for branch in "$@"; do
    origin_branches=$(git b -a | grep -e "origin/$branch")

    if [[ -z $origin_branches ]]; then
      echo "Missing from origin - skipping $branch"
      continue
    fi

    echo "Removing remote $branch"
    git push origin --delete $(git branch | grep "$branch")
  done
}

function remove_local() {
  for branch in "$@"; do
    local_branches=$(git b | grep -e "$branch")

    if [[ -z $local_branches ]]; then
      echo "Missing from local - skipping $branch"
      continue
    fi

    echo "Removing local $branch"
    git branch -D $(git branch | grep -e "$branch")
  done
}

if [[ -z "$1" || "$1" == "-h" ]]; then
	echo "Branch parameter is required."
	echo "Add"
	echo "# local branch name as argument"
	echo "# -m to remove all merged branches"
	echo "# -l to remove local branches from origin"
	echo "# -r to remove remote branches from origin"
	exit 1
fi

git fetch --all --prune
CURRENT_BRANCH=$(git b | grep "*" | cut -d "/" -f 2)

echo "Current branch: ${CURRENT_BRANCH}"
echo ""
CONFIRM=${CONFIRM:-n}

if [[ "$1" == "-m" ]]; then
  read -p "Merged branch? (main) " MERGED_BRANCH
  MERGED_BRANCH=${MERGED_BRANCH:-main}

	branches=$(git b -a --merged ${MERGED_BRANCH} | grep -v -e 'main' -e '*' -e "${CURRENT_BRANCH}" | grep -E "origin/feature|origin/bugfix|origin/release" | cut -d '/' -f 3-)

	echo -n "The following branches will be deleted from ORIGIN:"
	echo ""
	echo "$branches"
	echo ""
	read -p "To confirm insert [y/N]: " CONFIRM
	echo ""

	CONFIRM=${CONFIRM:-n}

	if [[ $CONFIRM == "y" || $CONFIRM == "yes" ]]; then
		for branch in $branches; do
      remove_remote $branch
      remove_local $branch
		done
	fi
elif [[ "$1" == "-l" ]]; then
	branches=$(git b | grep -v -e 'main' -e '*' -e "${CURRENT_BRANCH}")

	echo -n "The following branches will be deleted locally:"
	echo ""
	echo "$branches"
	echo ""
	read -p "To confirm insert [y/N]: " CONFIRM
	echo ""

	CONFIRM=${CONFIRM:-n}
	if [[ $CONFIRM == "y" || $CONFIRM == "yes" ]]; then
		for branch in $branches; do
      remove_local $branch
		done
	fi
elif [[ "$1" == "-r" ]]; then
	branches=$(git b | grep -v -e 'main' -e '*' -e "${CURRENT_BRANCH}")

	echo -n "The following branches will be deleted:"
	echo ""
	echo "$branches"
	echo ""
	read -p "To confirm insert [y/N]: " CONFIRM
	echo ""

	CONFIRM=${CONFIRM:-n}
	if [[ $CONFIRM == "y" || $CONFIRM == "yes" ]]; then
		for branch in $branches; do
      remove_remote $branch
      remove_local $branch
		done
	fi
else
  remove_remote "$@"
  remove_local "$@"
fi
