#!/bin/bash

source app_location.cfg

function get_branch() {
    BRANCH_TO_REFRESH="$1"

    if [[ -z "$BRANCH_TO_REFRESH" ]]; then
        GIT_BRANCH=$(git branch | grep "*")
        BRANCH=${GIT_BRANCH:2}
    else
        BRANCH="$BRANCH_TO_REFRESH"

        if [[ -z $(git branch | grep "$BRANCH") ]]; then
            GIT_BRANCH=$(git branch | grep "*")
            CURRENT_BRANCH=${GIT_BRANCH:2}

            echo "$BRANCH does not exist. Branch set to $CURRENT_BRANCH"

            BRANCH="$CURRENT_BRANCH"
        fi
    fi
}

function refresh() {
    API_DIR="$1"
    BRANCH_TO_REFRESH="$2"

    if [[ -d "$ROOT_DIR/$API_DIR" ]]; then
        cd "$ROOT_DIR/$API_DIR"
        echo "Working in $API_DIR ..."

        BRANCH=''
        ERROR_MESSAGE=''

        get_branch $BRANCH_TO_REFRESH

        echo "Fetching ..."
        gf &> /dev/null
        CHECKOUT_MESSAGE=$(git checkout "$BRANCH" 2>&1 > /dev/null)

        if [[ $? == 1 ]]; then
            echo "An error occurred when tried to checkout $BRANCH:"
            echo "$CHECKOUT_MESSAGE"
            exit 1
        fi

        echo "Pulling $BRANCH ..."
        git pull &> /dev/null

        echo -n "Installing dependencies "
        while true; do echo -n "."; sleep 1; done &
        trap 'kill $!' SIGTERM SIGKILL

        composer install &> /dev/null

        kill $!

        echo -e "\nDone."
        exit 0
    else
        echo "$ROOT_DIR/$API_DIR is not a directory."
        exit 1
    fi
}

function api_refresh() {
    DIR_TO_REFRESH="$1"
    BRANCH_TO_REFRESH="$2"

    if [[ -z "$DIR_TO_REFRESH" ]]; then
        refresh ${PWD##*/} $BRANCH_TO_REFRESH
    elif [[ "$DIR_TO_REFRESH" == "." ]]; then
        refresh ${PWD##*/} $BRANCH_TO_REFRESH
    else
        refresh $DIR_TO_REFRESH $BRANCH_TO_REFRESH
    fi

    exit 0
}

api_refresh $@