#!/bin/bash

source app_location.cfg

function get_branch() {
    if [[ -z "$BRANCH_TO_REFRESH" ]]; then
        GIT_BRANCH=$(git branch | grep "*")
        BRANCH=${GIT_BRANCH:2}
    else
        BRANCH="$BRANCH_TO_REFRESH"
        GIT_BRANCH=$(git branch | grep "*")
        CURRENT_BRANCH=${GIT_BRANCH:2}

        if [[ -n $(git branch | grep "$BRANCH") ]]; then
            git checkout "$BRANCH" 2> /dev/null
        else
            echo "$BRANCH does not exist. Pulling $CURRENT_BRANCH"
            BRANCH="$CURRENT_BRANCH"
        fi
    fi
}

function refresh() {
    API_DIR="$1"
    BRANCH_TO_REFRESH="$2"

    cd "$ROOT_DIR/$API_DIR"
    echo "Working in $API_DIR ..."

    BRANCH=''
    get_branch $BRANCH_TO_REFRESH

    echo "Fetching ..."
    gf &> /dev/null
    echo "Pulling $BRANCH ..."
    gitall pull &> /dev/null
    echo "Installing dependencies ..."
    cpinstall &> /dev/null
}

function api_refresh() {
    DIR_TO_REFRESH="$1"
    BRANCH_TO_REFRESH="$2"

    if [[ -z "$DIR_TO_REFRESH" ]]; then
        for API_DIR in $(find "$ROOT_DIR" -maxdepth 1 -name "*-api"); do
            refresh ${API_DIR##*/} $BRANCH_TO_REFRESH
        done
    elif [[ "$DIR_TO_REFRESH" == "." ]]; then
        refresh ${PWD##*/} $BRANCH_TO_REFRESH
    else
        refresh $DIR_TO_REFRESH $BRANCH_TO_REFRESH
    fi
}

api_refresh $@