#!/bin/bash

# boot dir size in bytes: 463832
BOOT_SIZE=$(du -s /boot/ | cut -d "/" -f 1 | xargs)
# max dir size for boot dir
MAX_DIR_SIZE=450000

if [[ $BOOT_SIZE -lt $MAX_DIR_SIZE ]]; then
  echo "size of /boot/ is less than $MAX_DIR_SIZE"
  exit
else
  echo "size of /boot/ is $BOOT_SIZE out of $MAX_DIR_SIZE"
  echo ""
  read -p "To proceed insert (y/n): " CONFIRM
  CONFIRM=${CONFIRM:-y}
  echo ""
  if [[ $CONFIRM =~ ^[Yy]$ ]]; then
    echo "Cleaning up /boot/"
  else
    exit
  fi
fi

FILES=$(ls /boot/ | grep "\-generic")
OLDEST_MAJOR_VERSION=$(echo "$OLDEST_VERSION" | cut -d "." -f 1)
OLDEST_MINOR_VERSION=$(echo "$OLDEST_VERSION" | cut -d "." -f 2)
OLDEST_PATCH_VERSION=$(echo "$OLDEST_VERSION" | cut -d "." -f 3 | cut -d "-" -f 1)
OLDEST_SUFFIX_VERSION=$(echo "$OLDEST_VERSION" | cut -d "-" -f 2)

for FILE in $FILES
do
  VERSION=$(echo $FILE | cut -d "-" -f 2-3)
  VERSION_SUFFIX=$(echo $VERSION | tr -d '.-')
  MAJOR_VERSION=$(echo "$VERSION" | cut -d "." -f 1)
  MINOR_VERSION=$(echo "$VERSION" | cut -d "." -f 2)
  PATCH_VERSION=$(echo "$VERSION" | cut -d "." -f 3 | cut -d "-" -f 1)
  SUFFIX_VERSION=$(echo "$VERSION" | cut -d "-" -f 2)

  if [[ $MAJOR_VERSION -lt $OLDEST_MAJOR_VERSION ]]; then
    OLDEST_MAJOR_VERSION="$MAJOR_VERSION"

    if [[ $MINOR_VERSION -lt $OLDEST_MINOR_VERSION ]]; then
      OLDEST_MINOR_VERSION="$MINOR_VERSION"

      if [[ $PATCH_VERSION -lt $OLDEST_PATCH_VERSION ]]; then
        OLDEST_PATCH_VERSION="$PATCH_VERSION"

        if [[ $SUFFIX_VERSION -lt $OLDEST_SUFFIX_VERSION ]]; then
          OLDEST_SUFFIX_VERSION="$SUFFIX_VERSION"
        fi
      fi
    fi
  fi
done

OLDEST_VERSION="$OLDEST_MAJOR_VERSION.$OLDEST_MINOR_VERSION.$OLDEST_PATCH_VERSION-$OLDEST_SUFFIX_VERSION"
LIST_OF_FILES_TO_CLEAN=$(ls /boot/ | grep "$OLDEST_VERSION")
echo ""
echo "list of files to remove:"
echo ""
for FILE in $LIST_OF_FILES_TO_CLEAN
do
  echo "/boot/$FILE"
done

echo ""
read -p "To confirm insert (y/n): " CONFIRM
CONFIRM=${CONFIRM:-y}
echo ""

if [[ $CONFIRM =~ ^[Yy]$ ]]; then
  for FILE in $LIST_OF_FILES_TO_CLEAN
  do
    rm /boot/$FILE
  done
fi

BOOT_SIZE=$(du -s /boot/ | cut -d "/" -f 1 | xargs)

echo "new size of /boot/ is $BOOT_SIZE out of $MAX_DIR_SIZE"
