#!/bin/bash

source app_location.cfg

for API_DIR in $(find "${ROOT_DIR}" -maxdepth 1 -name "*-api"); do
    cd $(dirname "$API_DIR")

    for d in $(find "${API_DIR}" -maxdepth 1 -name composer.json); do
        cd $(dirname "$d")
        composer install
    done
done
