#!/bin/bash

CURRENT_DIR=${PWD##*/}
DOCKER_PHP_CONTAINER_NAME="$(echo $CURRENT_DIR | sed -e 's/-/_/g')_phpfpm"
DOCKER_PHP_CONTAINER_ID="$(docker container ls -q --filter name=$DOCKER_PHP_CONTAINER_NAME)"

docker exec -ti "$DOCKER_PHP_CONTAINER_ID" bin/console --env=docker "$@"
