#!/bin/bash

function show_help() {
    cat << EOF 
Usage: deploy-api [OPTION...]

  -a    API to be deployed (optional)
          - if not passed current directory will be used.
          - must be an existing directory in "ROOT_DIR"
          - pass "." to use current directory
  -b    Branch to be used (optional)
          - if not passed current branch will be used.
          - if passed branch does not exist current branch will be used.
  -r    To rebuild containers
  -?    Prints this help
EOF
}

function in_array() {
: '
  Usage: in_array [NEEDLE] [HAYSTACK...]

  $1 must be an element to be searched in $2
'
  NEEDLE=$1
  HAYSTACK=${@:2}

  for element in $HAYSTACK
  do
    if [[ $element == $NEEDLE ]]; then
      return 0
      fi
  done

  return 1
}

function find_docker_php_container_id() {
: '
  Usage: find_docker_php_container_id [DIRECTORY]

  $1 must be a directory with name of a docker container. 
  e.g. admin-api -> admin_api_phpfpm will be searched
'
  DOCKER_PHP_CONTAINER_NAME="$(echo $1 | sed -e 's/-/_/g')_phpfpm"
  DOCKER_PHP_CONTAINER_ID="$(docker container ls -q --filter name=$DOCKER_PHP_CONTAINER_NAME)"

  return 0
}

function is_docker_container_running() {
: '
  $1 must be a docker container identifier
'
  docker inspect -f '{{.State.Running}}' "$1"
}

function wait_docker_container_to_start() {
: '
  $1 must be a docker container identifier
'
  until [[ "$(is_docker_container_running "$1")"!="true" ]]; do
    sleep 0.1;
  done;
}

function run_commands() {
: '
  $1 must be a docker container identifier
  $2 must be an array of docker executable php commands + its arguments
'
  for command in "${@:2}"; do
    dcr -c "$1" "$command"
  done
}

function run_doctrine_schema_update() {
: '
  $1 must be the name of app. e.g. admin-api
  $2 must be a docker container identifier
'
  NO_DATABASE_SCHEMA_UPDATE_NEEDED=("common-docker" "anonymization-api" "chat-api" "gateway-api" "mailer-api" "push-api" "search-api" "url-shortener-api")

  in_array "$1" ${NO_DATABASE_SCHEMA_UPDATE_NEEDED[@]}

  if [[ $? -ne 0 ]]; then
    echo "Updating database schema..."

    dcr -c "$2" o:s:u --dump-sql
    dcr -c "$2" o:s:u -f
  else
    echo "Skipping database schema update."
  fi
}

API_TO_DEPLOY=""
BRANCH_TO_DEPLOY=""
REBUILD_CONTAINERS=false

while getopts "a:b:rh?" opt; do
    case "$opt" in
    a)  API_TO_DEPLOY=$OPTARG
        ;;
    b)  BRANCH_TO_DEPLOY=$OPTARG
        ;;
    r)  REBUILD_CONTAINERS=true
        ;;
    h|\?)
        show_help
        exit 0
        ;;
    esac
done
shift $((OPTIND -1))

CURRENT_DIR=${PWD##*/}
DIR_TO_USE="$API_TO_DEPLOY"

if [[ -z "$API_TO_DEPLOY" ]]; then
  DIR_TO_USE="$CURRENT_DIR"
elif [[ "$API_TO_DEPLOY" == "." ]]; then
  DIR_TO_USE="$CURRENT_DIR"
fi

if [[ -z "$BRANCH_TO_DEPLOY" ]]; then
  api-refresh -d $DIR_TO_USE
else
  api-refresh -d $DIR_TO_USE -b $BRANCH_TO_DEPLOY
fi

DOCKER_PHP_CONTAINER_ID=""

find_docker_php_container_id $DIR_TO_USE

if [[ "$REBUILD_CONTAINERS" == true ]]; then
  cd "$DIR_TO_USE"

  if [[ -n "$DOCKER_PHP_CONTAINER_ID" ]] && [[ "$(is_docker_container_running $DOCKER_PHP_CONTAINER_ID)" ]]; then
      docker-compose down --remove-orphans &> /dev/null
  fi

  echo "Rebuilding docker containers..."
  docker-compose up -d --build &> /dev/null

  find_docker_php_container_id $DIR_TO_USE

  if [[ -z "$DOCKER_PHP_CONTAINER_ID" ]]; then
    echo "Cannot start docker container of $DIR_TO_USE"
    exit 1
  fi

  wait_docker_container_to_start $DOCKER_PHP_CONTAINER_ID
fi

echo "$DOCKER_PHP_CONTAINER_ID is up-to-date and running."

run_doctrine_schema_update $DIR_TO_USE $DOCKER_PHP_CONTAINER_ID

ADMIN_API_COMMANDS=("admin:action:import-actions")
DATA_PRIVACY_API_COMMANDS=("data-right:import")
GATEWAY_API_COMMANDS=("routes:generate:from-openapi-services")

echo "Running commands in $DIR_TO_USE..."

if [[ $DIR_TO_USE == "admin-api" ]]; then
  run_commands $DOCKER_PHP_CONTAINER_ID $ADMIN_API_COMMANDS
elif [[ $DIR_TO_USE == "data-privacy-api" ]]; then
  run_commands $DOCKER_PHP_CONTAINER_ID $DATA_PRIVACY_API_COMMANDS
elif [[ $DIR_TO_USE == "gateway-api" ]]; then
  run_commands $DOCKER_PHP_CONTAINER_ID $GATEWAY_API_COMMANDS
fi