#!/bin/bash

DOCKER_FILE=$(find ./ -maxdepth 1 -name "docker-compose.yml")

if [ ! -z $DOCKER_FILE ]
then
    docker-compose down && docker-compose up -d --build
else
    echo "docker-compose.yml cannot be found in $(pwd)"
fi