#!/bin/bash

DOCKER_FILE=$(find ./ -maxdepth 1 -name "docker-compose.yml")

if [ ! -z $DOCKER_FILE ]; then
    docker-compose down
    docker-compose up -d --build

    exit 0
else
    echo "docker-compose.yml cannot be found in $(pwd)"
    exit 1
fi