#!/bin/bash

if [[ -z "$1" || "$1" == "-h" ]]; then
	echo "Branch parameter is required."
	echo "Add" 
	echo "# local branch name as argument"
	echo "# -m to remove all merged branches"
	echo "# -l to remove local branches from origin"
	echo "# -r to remove remote branches from origin"
	exit 1
fi

if [[ "$1" == "-m" ]]; then
	branches=$(git b -a --merged | grep -E "origin/feature|origin/bugfix|origin/release" | cut -d '/' -f 3-)

	echo -n "The following branches will be deleted from ORIGIN:"
	echo ""
	echo "$branches"
	echo ""
	echo "To confirm insert (y/n):"
	echo ""
	read confirm

	confirm=${confirm:-y}

	if [[ $confirm == "y" || $confirm == "yes" ]]; then
		for branch in $branches; do
			git push origin --delete "$branch"
			git branch -D "$branch"
		done
	fi
elif [[ "$1" == "-l" ]]; then
	branches=$(git b | grep -v -e 'master' -e '*')

	echo -n "The following branches will be deleted locally:"
	echo ""
	echo "$branches"
	echo ""
	echo "To confirm insert (y/n):"
	echo ""
	read confirm

	confirm=${confirm:-y}
	if [[ $confirm == "y" || $confirm == "yes" ]]; then
		for branch in $branches; do
			git b -D "$branch"
		done
	fi
elif [[ "$1" == "-r" ]]; then
	branches=$(git b | grep -v -e 'master' -e '*')

	echo -n "The following branches will be deleted:"
	echo ""
	echo "$branches"
	echo ""
	echo "To confirm insert (y/n):"
	echo ""
	read confirm

	confirm=${confirm:-y}
	if [[ $confirm == "y" || $confirm == "yes" ]]; then
		for branch in $branches; do
			git push origin --delete "$branch"
			git branch -D "$branch"
		done
	fi
else
	git push origin --delete $(git branch | grep "$1")
	git branch -D $(git branch | grep "$1")
fi
