#!/bin/bash

if [[ -z "$1" || "$1" == "-h" ]]; then
	echo "Branch parameter is required."
	echo "Add"
	echo "# local branch name as argument"
	echo "# -m to remove all merged branches"
	echo "# -l to remove local branches from origin"
	echo "# -r to remove remote branches from origin"
	exit 1
fi

git fetch --all --prune
CURRENT_BRANCH=$(git b | grep "*" | cut -d "/" -f 2)

echo "Current branch: ${CURRENT_BRANCH}"
echo ""
CONFIRM=${CONFIRM:-n}

if [[ "$1" == "-m" ]]; then
  read -p "Merged branch? (master) " MERGED_BRANCH
  MERGED_BRANCH=${MERGED_BRANCH:-master}

	branches=$(git b -a --merged ${MERGED_BRANCH} | grep -v -e 'master' -e '*' -e "${CURRENT_BRANCH}" | grep -E "origin/feature|origin/bugfix|origin/release" | cut -d '/' -f 3-)

	echo -n "The following branches will be deleted from ORIGIN:"
	echo ""
	echo "$branches"
	echo ""
	read -p "To confirm insert (y/n): " CONFIRM
	echo ""

	CONFIRM=${CONFIRM:-n}

	if [[ $CONFIRM == "y" || $CONFIRM == "yes" ]]; then
		for branch in $branches; do
			git push origin --delete "$branch"
			git branch -D "$branch"
		done
	fi
elif [[ "$1" == "-l" ]]; then
	branches=$(git b | grep -v -e 'master' -e '*' -e "${CURRENT_BRANCH}")

	echo -n "The following branches will be deleted locally:"
	echo ""
	echo "$branches"
	echo ""
	read -p "To confirm insert (y/n): " CONFIRM
	echo ""

	CONFIRM=${CONFIRM:-n}
	if [[ $CONFIRM == "y" || $CONFIRM == "yes" ]]; then
		for branch in $branches; do
			git b -D "$branch"
		done
	fi
elif [[ "$1" == "-r" ]]; then
	branches=$(git b | grep -v -e 'master' -e '*' -e "${CURRENT_BRANCH}")

	echo -n "The following branches will be deleted:"
	echo ""
	echo "$branches"
	echo ""
	read -p "To confirm insert (y/n): " CONFIRM
	echo ""

	CONFIRM=${CONFIRM:-n}
	if [[ $CONFIRM == "y" || $CONFIRM == "yes" ]]; then
		for branch in $branches; do
			git push origin --delete "$branch"
			git branch -D "$branch"
		done
	fi
else
	git push origin --delete $(git branch | grep "$1")
	git branch -D $(git branch | grep "$1")
fi
