#!/bin/bash

function show_help() {
    cat << EOF 
Usage: ip-up [OPTION...]

  -a    To add routes
  -d    To delete routes
  -?    Prints this help
EOF
}

function route_add() {
    DEVICE=$(ip a | grep "POINTOPOINT" | awk '{print $2}' | cut -d ":" -f 1);

    if [[ -n $DEVICE ]]; then
        ip route add "$1" dev "$DEVICE"

        return 0
    fi

    return 1
}

function is_route_existing() {
    ROUTE=$(ip route | grep "$1")

    if [[ -z $ROUTE ]]; then
        return 0
    fi

    return 1
}

function add_routes() {
    COUNT=0

    for route in "${ROUTES[@]}"; do
        is_route_existing "$route"

        if [[ $? == 0 ]]; then
            route_add "$route"

            if [[ $? == 0 ]]; then
                ((COUNT++))
            fi
        fi
    done

    echo "$COUNT routes added"
}

function delete_routes() {
    COUNT=0

    for route in "${ROUTES[@]}"; do
        is_route_existing "$route"

        if [[ $? == 1 ]]; then
            ip route del "$route"

            if [[ $? == 0 ]]; then
                ((COUNT++))
            fi
        fi
    done

    echo "$COUNT routes deleted"
}

UNUSED_ROUTES=(\
 "192.168.0.0/21"
 "109.71.162.224/32"\
 "109.71.162.126/32"
)

ROUTES=(\
 "192.168.1.0/24"\
 "192.168.45.0/24"\
 "192.168.46.0/24"\
 "192.168.47.0/24"\
 "192.168.48.0/24"\
 "192.168.49.0/24"\
 "192.168.199.98"\
 "192.168.199.134"\
 "185.13.89.199"\
 "185.13.89.201"\
 "185.13.90.100"\
 "109.71.162.126"\
 "95.128.124.116"\
 "5.159.216.0/24"\
 "5.159.216.64"
)

VPN_DEVICE="POINTOPOINT"

if [[ -n "$1" ]]; then
    VPN_DEVICE="$1"
fi

while getopts "adh?" opt; do
    case "$opt" in
    a)  add_routes
        ;;
    d)  delete_routes 
        ;;
    h|\?)
        show_help
        exit 0
        ;;
    esac
done
shift $((OPTIND -1))

if [ $OPTIND -eq 1 ]; then 
    show_help
    exit 1
else
    ip route
fi
