#!/bin/bash

function get_remote_branch() {
	GIT_BRANCH=$(git branch | grep "*")
	BRANCH=${GIT_BRANCH:2}
	REMOTE_BRANCH=$(echo "$BRANCH" | sed 's/\//\-/g' | cut -f 1-3 -d "-" | tr '[:upper:]' '[:lower:]')

	REMOTE_BRANCH="master"
}

function create_remote_paths() {
	REMOTE_PATHS=()

	if [[ -n "${@:2}" ]]; then
		for dir in "${@:2}"; do
			REMOTE_PATHS+=(/home/peter.pecosz/projects/"$dir"/"$REMOTE_BRANCH"/)
		done
	else
		REMOTE_PATHS=(/home/peter.pecosz/projects/"$CURRENT_DIR"/"$REMOTE_BRANCH"/)
	fi
}

DIR=$(pwd)

if [[ -n "$1" ]]; then
    DIR=$(realpath "$1")
    cd $DIR
fi

CURRENT_DIR=${PWD##*/}
LOG_DIR=/var/log/jasmin-sync
LOG_FILE="$LOG_DIR"/"$CURRENT_DIR".log

if [[ ! -f "$LOG_FILE"  ]]; then
	mkdir -p "$LOG_DIR"
	touch "$LOG_FILE"
fi


REMOTE_BRANCH=""

get_remote_branch
echo "Remote branch used: $REMOTE_BRANCH"

REMOTE_PATHS=()

create_remote_paths $@

for REMOTE_DIR in ${REMOTE_PATHS[@]}
do
	if ssh dhdevel "[ ! -d $REMOTE_DIR ]"; then
		ssh dhdevel "mkdir -p $REMOTE_DIR"
	fi
done

while inotifywait -r -o "$LOG_FILE" --format "[$(date +"%Y-%m-%d %T")] %w %e %f" -e create,modify,delete,move --exclude=".idea|.git|.*___jb_tmp___" "$DIR"/; do
	get_remote_branch

	REMOTE_PATHS=()

	create_remote_paths $@

	for REMOTE_DIR in ${REMOTE_PATHS[@]}
	do
		echo "Sync started to $REMOTE_DIR"
		if [[ -f "$DIR/.rsync_exclude" ]]; then
			rsync -rae ssh "$DIR"/* dhdevel:"$REMOTE_DIR" --exclude-from="$DIR/.rsync_exclude"
		else
			rsync -rae ssh "$DIR"/* dhdevel:"$REMOTE_DIR" 
		fi
	done
done