#!/bin/bash

PIDS=$(ps aux | grep $USER | grep jasmin | awk '{print $2}')
PNAMES=$(ps aux | grep $USER | grep jasmin | awk '{print $18}')

if [[ -n $PIDS ]]; then
	kill $PIDS

	for path in $PNAMES; do
		pname=$(realpath $path)
		echo "Sync of ${pname##*/} killed."
	done
else
	echo "Sync process cannot be found."
fi