#!/bin/bash -x

function connect() {
	pppd call lubet
	sleep 3
	/usr/local/bin/ip-up -a
}

DEVICE=$(ip a | grep "ppp0:")

if [[ -z $DEVICE ]]; then
    echo "PPP device not found. Connecting..."
    connect
    exit 0
fi

DEVICE_STATUS=$(nmcli device status | grep ppp | awk '{print $3}')

if [[ $DEVICE_STATUS == 'connected' ]]; then
    echo 'Already connected.'
    exit 2
fi

connect
exit 0