#!/bin/bash

function show_help() {
    cat << EOF 
Usage: satis-inspect [OPTION...]

  -u    username of private satis
  -c    path of composer.json to parse
  -?    Prints this help
EOF
}

function read_password {
  echo "Enter password for private satis:"
  read -s PASSWORD
}

function flag {
  packageCount=${#1}

  echo -n "======"
  for i in $(seq 1 $packageCount); do
    echo -n "="
  done
  echo -n "======"
  echo ""
  echo "===== $1 ====="

  echo -n "======"
  for i in $(seq 1 $packageCount); do
    echo -n "="
  done

  echo -n "======"
  echo ""
}

USER=""
PASSWORD=""
COMPOSER_JSON=""

while getopts "u:c:h?" opt; do
    case "$opt" in
    u)  USER=$OPTARG
        ;;
    c)  COMPOSER_JSON=$(realpath $OPTARG)
        ;;
    h|\?)
        show_help
        exit 0
        ;;
    esac
done
shift $((OPTIND -1))

if [[ -z "$USER" ]]; then
  echo "User is required."
  exit 1
fi

if [[ ! -r "$COMPOSER_JSON" ]]; then
  echo "$COMPOSER_JSON is not a file"
  exit 1
fi

read_password

while read package_line ; do
  package=$(echo $package_line | cut -d \" -f 2)
  package_version_requirement=$(echo $package_line | cut -d \" -f 4)

  flag $package

  curl --user "$USER":"$PASSWORD" "https://satis-private.doclerholding.com/#$package" 2> /dev/null | grep "<a href=\"https://satis-private.doclerholding.com/dist/$package" -A0 -B0 | cut -d \> -f 2 | cut -d \< -f 1 | awk 'NR<=5{print $1}'

  echo ""
  echo "Current version requirement: $package_version_requirement"
  echo ""
  echo ""
done < <(cat "$COMPOSER_JSON" | jq -r .require | grep "dh-")