#!/bin/bash

DEVICE=$(ip a | grep "sscvpn" -m 1 | awk '{print $2}' | cut -d ":" -f 1);

if [[ -n $DEVICE ]]; then
	read -p "$DEVICE already exists. Do you want to reconnect? (y/n)" -n 1 -r confirm

	confirm=${confirm:-y}

	echo ""

	if [[ $confirm =~ ^[Yy]$ ]]; then
	    ip link set $DEVICE down
	    ip link delete $DEVICE
	    pgrep -f client-sscvpn.conf | xargs kill $1
	    echo "device removed: $DEVICE"
		echo "reconnecting..."
	else
		exit 0
	fi
fi

openvpn --daemon --config /etc/openvpn/client/ssc/client-sscvpn.conf

COUNTER=0
while [[ -z $DEVICE && $COUNTER -lt 5 ]];
do
	echo -n "."
	DEVICE=$(ip a | grep "sscvpn" -m 1 | awk '{print $2}' | cut -d ":" -f 1)
	(( COUNTER++ ))
	sleep 1
done
echo ""

if [[ -n $DEVICE ]]; then
	echo "Connected to $DEVICE"
else
	echo "Unable to connect"
    pgrep -f client-sscvpn.conf | xargs kill $1
fi