#!/bin/bash

if [[ ! -f $HOME/.ssh/config ]]; then
  echo "touching $HOME/.ssh/config"
  touch $HOME/.ssh/config
fi

echo "Host dhdevel
    HostName 10.128.130.18
    Port 22
    User peter.pecosz" > $HOME/.ssh/config
echo "'dhdevel' has been added to ssh config as a Host"
