#!/bin/bash

if [[ ! -f $HOME/.ssh/config ]]; then
  echo "touching $HOME/.ssh/config"
  touch $HOME/.ssh/config
fi

read -p "SSH Host short name: " HOST
read -p "SSH Host IP: " IP

echo "Host $HOST
    HostName $IP
    Port 22
    User peter.pecosz
" >> $HOME/.ssh/config

echo "'$HOST' has been added to ssh config as a Host"
