#!/bin/bash

PHP_VERSION_DESIRE=${1:-8.1}
FILE="/usr/bin/php$PHP_VERSION_DESIRE"
ALT_FILE=/etc/alternatives/php

if [ ! -f $FILE ]; then
    echo "Cannot swap PHP to $PHP_VERSION_DESIRE"
    echo "$FILE does not exist."
    exit 255
fi

rm $ALT_FILE && ln -s $FILE $ALT_FILE
echo "Swapped PHP version."
php -v | grep "PHP $PHP_VERSION_DESIRE" -A 0 -B 0
