#!/bin/sh

if [[ -z "$1" || "$1" == "-h" ]]; then
	echo "Helps to create symlinks of custom scripts to be executable."
	echo "Filename parameter is required."
	exit 1
fi

if [[ ! -e "$1" ]]; then
  echo "$1 does not exist, failed to create symlink"
  exit 1
fi

FILENAME=$(basename "$1")
EXECUTABLE=${FILENAME%%.*}
FILEPATH=$(realpath "$1")
BIN_PATH="/usr/local/bin/$EXECUTABLE"

chmod +x "$FILEPATH"

if [[ -e "$BIN_PATH" ]]; then
  echo "$BIN_PATH already exists, skipped to create symlink"
else
  ln -s "$FILEPATH" "$BIN_PATH"
fi

