#!/bin/bash

echo "Creating symlink for symlink"
symlink symlink

echo "Creating symlink for cpi"
symlink cpi

echo "Creating symlink for cpr"
symlink cpr

echo "Creating symlink for dfps"
symlink ./docker/dfps

echo "Creating symlink for gadda"
symlink ./git/gadda

echo "Creating symlink for gbdel"
symlink ./git/gbdel

echo "Creating symlink for gcm"
symlink ./git/gcm

echo "Creating symlink for gd"
symlink ./git/gd

echo "Creating symlink for gds"
symlink ./git/gds

echo "Creating symlink for gf"
symlink ./git/gf

echo "Creating symlink for glog"
symlink ./git/glog

echo "Creating symlink for gmerge"
symlink ./git/gmerge

echo "Creating symlink for grs"
symlink ./git/grs

echo "Creating symlink for gsgo"
symlink ./git/gsgo

echo "Creating symlink for gspull"
symlink ./git/gspull

echo "Creating symlink for gtagl"
symlink ./git/gtagl

echo "Creating symlink for subl"
symlink /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl
